name: Generate Code from Blueprints

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for getting proper diff
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate code from blueprints
        uses: vtemian/blueprints-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          src: '.'  # Process markdown files in root
          output-dir: './src'
          process-only-changed: true
          auto-commit: true
          commit-branch: 'generated'  # Commit to separate branch
          base-branch: 'main'
          commit-message: 'feat: auto-generate code from blueprints'
          fail-on-error: false

      - name: Create Pull Request
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          EXISTING_PR=$(gh pr list --base main --head generated --state open --json number --jq '.[0].number' || echo "")
          
          if [ -z "$EXISTING_PR" ]; then
            # Create new PR
            gh pr create \
              --base main \
              --head generated \
              --title "Auto-generated code from blueprints" \
              --body "This PR contains auto-generated code from blueprint markdown files.
              
              Generated from commit: ${{ github.sha }}
              
              Please review the generated code before merging."
          else
            echo "PR #$EXISTING_PR already exists for generated branch"
          fi