name: Generate Task API Example

on:
  push:
    paths:
      - 'examples/task-api/**/*.md'
      - '.github/workflows/example-task-api.yml'
  workflow_dispatch:
    inputs:
      language:
        description: 'Target programming language'
        required: true
        default: 'python'
        type: choice
        options:
          - python
          - javascript
          - typescript
          - go

jobs:
  generate-task-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate Task API
        uses: ./
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          src: 'examples/task-api'
          output-dir: './generated/task-api'
          language: ${{ github.event.inputs.language || 'python' }}
          
      - name: Upload generated code
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: task-api-${{ github.event.inputs.language || 'python' }}
          path: |
            ./generated/task-api
            ./examples/task-api/**/*.py
            ./examples/task-api/**/*.js
            ./examples/task-api/**/*.ts
            ./examples/task-api/**/*.go
          if-no-files-found: warn
          
      - name: Display generated files
        if: always()
        run: |
          echo "Generated Task API files:"
          echo "Checking output directory:"
          if [ -d "./generated/task-api" ]; then
            find ./generated/task-api -type f | head -20
          fi
          echo "Checking source directory for generated files:"
          find ./examples/task-api -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.go" \) 2>/dev/null | head -20 || echo "No generated files found"